baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Hugo Photoalbum Test'

[module]
  [[module.imports]]
    path = "github.com/cornelius/hugo-photoalbum-theme"

[params]
  defaultTheme = "dark"
